### ISSUE TITLE
Stops listening on UDP port after getting invalid json

### ISSUE THREAD

**Issue by elecnix** [messagebird/pushprom#1]
This will cause prompush to return from the `listenUDP` function, causing it to close `serverConn`:

`echo "hello" | nc --udp localhost -p 9090`

logs:

`2016/11/09 17:20:37 udp.go:36: Error:  invalid character 'h' looking for beginning of value`

then a second `nc` prints:

`Ncat: Connection refused.`

**Comment by samwierema** [comment]
Thanks for opening an issue @elecnix! I've asked a colleague to confirm the issue and hopefully we can patch it a.s.a.p.

**Comment by samwierema** [comment]
The issue should be resolved with the latest release @elecnix. Let us know if you find the same to be true!

**Comment by elecnix** [comment]
Thanks!
