### ISSUE TITLE
Invalid label value "1 \xc0\xa7\xc0...." prevents prometheus from scraping pushprom

### ISSUE THREAD

**Issue by marcelcorso** [messagebird/pushprom#11]
![screen shot 2017-01-23 at 10 29 03](https://cloud.githubusercontent.com/assets/19642/22198441/d2de7b4e-e156-11e6-9f7f-d5c16a0b285e.png)

invalid label values prevent prometheus from scraping pushprom. 

Should this kind of values be filtered by pushprom or prometheus golang client?

**Comment by samwierema** [comment]
After further investigation we found this issue is not caused by Pushprom.
